setwd("C:/Users/Adrian/Desktop/Magisterka/WSP/Kod_R")
library(officer)
library(ggplot2)

pres <- read_pptx(path = "Szablon.pptx")
#pres <- add_slide()
paragraph <- fpar(ftext("Przykladowy tytul", fp_text(color = "black", font.size = 40, bold = TRUE)))
pres <- ph_with(pres, value = paragraph, location = ph_location(left = 4,top = 0.5,width = 6,height = 2))
frame <- data.frame(a = 1:5, b = 6:10, c = 11:15)
pres <- ph_with(pres, value = frame, location = ph_location(left = 8.5,top = 4,width = 4,height = 2))
sample_plot <- ggplot(data = frame) + geom_point(mapping = aes(1:5, a), size = 3) + theme_minimal()
pres <- ph_with(pres, value = sample_plot, location = ph_location(left = 1,top = 1.5,width = 6,height = 5), bg = "lightblue")
pres<- ph_with(pres, external_img("R_logo.svg.png", width = 2.78, height = 2.12), location = ph_location(left = 9.5,top = 1.2, width = 4,height = 2), use_loc_size = FALSE)
print(pres, target = "przyklad.pptx")